---@meta

---@class UWBP_Settings_Page_Game_C : UWBP_Settings_Page_C
---@field UberGraphFrame FPointerToUberGraphFrame
---@field VerticalBox_CrashReportSettings UVerticalBox
---@field WBP_Button_Generic_RevertToDefault UWBP_Button_Generic_C
---@field WBP_Settings_Entry_Choice_AutoClimbMode UWBP_Settings_Entry_Choice_AutoClimbMode_C
---@field WBP_Settings_Entry_Choice_Toggle_AutoSkipAlreadySeenEvents UWBP_Settings_Entry_Choice_Toggle_C
---@field WBP_Settings_Entry_Choice_Toggle_AutoUploadCrash UWBP_Settings_Entry_Choice_Toggle_C
---@field WBP_Settings_Entry_Choice_Toggle_CameraOscillation UWBP_Settings_Entry_Choice_Toggle_C
---@field WBP_Settings_Entry_Choice_Toggle_DisplayAchievementNotifications UWBP_Settings_Entry_Choice_Toggle_C
---@field WBP_Settings_Entry_Choice_Toggle_DisplayDamageValues UWBP_Settings_Entry_Choice_Toggle_C
---@field WBP_Settings_Entry_Choice_Toggle_DisplayEnemyGauges UWBP_Settings_Entry_Choice_Toggle_C
---@field WBP_Settings_Entry_Choice_Toggle_DisplayHealValues UWBP_Settings_Entry_Choice_Toggle_C
---@field WBP_Settings_Entry_Choice_Toggle_DisplayHPAboveGauge UWBP_Settings_Entry_Choice_Toggle_C
---@field WBP_Settings_Entry_Choice_Toggle_DisplayPlayerUI UWBP_Settings_Entry_Choice_Toggle_C
---@field WBP_Settings_Entry_Choice_Toggle_DisplayTutorial UWBP_Settings_Entry_Choice_Toggle_C
---@field WBP_Settings_Entry_Choice_Toggle_DodgeStillHoldDown UWBP_Settings_Entry_Choice_Toggle_C
---@field WBP_Settings_Entry_Slider_CameraShake UWBP_Settings_Entry_Slider_C
---@field WBP_Settings_Entry_Slider_LowHPFeedbackOpacity UWBP_Settings_Entry_Slider_C
local UWBP_Settings_Page_Game_C = {}

---@param MyGeometry FGeometry
---@param InFocusEvent FFocusEvent
---@return FEventReply
function UWBP_Settings_Page_Game_C:OnFocusReceived(MyGeometry, InFocusEvent) end
function UWBP_Settings_Page_Game_C:ResetToDefault() end
function UWBP_Settings_Page_Game_C:SetupPage() end
function UWBP_Settings_Page_Game_C:Construct() end
---@param KeyEvent FKeyEvent
function UWBP_Settings_Page_Game_C:BndEvt__WBP_Settings_Page_Game_WBP_Button_Generic_RevertToDefault_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature(KeyEvent) end
---@param ToggleValue boolean
function UWBP_Settings_Page_Game_C:BndEvt__WBP_Settings_Page_Game_WBP_Settings_Entry_Choice_Toggle_DodgeStillHoldDown_K2Node_ComponentBoundEvent_2_OnToggle__DelegateSignature(ToggleValue) end
---@param ToggleValue boolean
function UWBP_Settings_Page_Game_C:BndEvt__WBP_Settings_Page_Game_WBP_Settings_Entry_Choice_Toggle_DisplayDamageValues_K2Node_ComponentBoundEvent_3_OnToggle__DelegateSignature(ToggleValue) end
---@param ToggleValue boolean
function UWBP_Settings_Page_Game_C:BndEvt__WBP_Settings_Page_Game_WBP_Settings_Entry_Choice_Toggle_DisplayHealValues_K2Node_ComponentBoundEvent_4_OnToggle__DelegateSignature(ToggleValue) end
---@param ToggleValue boolean
function UWBP_Settings_Page_Game_C:BndEvt__WBP_Settings_Page_Game_WBP_Settings_Entry_Choice_Toggle_DisplayHPAboveGauge_K2Node_ComponentBoundEvent_5_OnToggle__DelegateSignature(ToggleValue) end
---@param ToggleValue boolean
function UWBP_Settings_Page_Game_C:BndEvt__WBP_Settings_Page_Game_WBP_Settings_Entry_Choice_Toggle_CameraOscillation_K2Node_ComponentBoundEvent_9_OnToggle__DelegateSignature(ToggleValue) end
---@param ToggleValue boolean
function UWBP_Settings_Page_Game_C:BndEvt__WBP_Settings_Page_Game_WBP_Settings_Entry_Choice_Toggle_DisplayPlayerUI_K2Node_ComponentBoundEvent_8_OnToggle__DelegateSignature(ToggleValue) end
---@param ToggleValue boolean
function UWBP_Settings_Page_Game_C:BndEvt__WBP_Settings_Page_Game_WBP_Settings_Entry_Choice_Toggle_DisplayEnemyGauges_K2Node_ComponentBoundEvent_10_OnToggle__DelegateSignature(ToggleValue) end
---@param ToggleValue boolean
function UWBP_Settings_Page_Game_C:BndEvt__WBP_Settings_Page_Game_WBP_Settings_Entry_Choice_Toggle_AutoUploadCrash_K2Node_ComponentBoundEvent_11_OnToggle__DelegateSignature(ToggleValue) end
---@param Value double
function UWBP_Settings_Page_Game_C:BndEvt__WBP_Settings_Page_Game_WBP_Settings_Entry_Slider_CameraShake_K2Node_ComponentBoundEvent_7_OnSliderValueChanged__DelegateSignature(Value) end
---@param ToggleValue boolean
function UWBP_Settings_Page_Game_C:BndEvt__WBP_Settings_Page_Game_WBP_Settings_Entry_Choice_Toggle_DisplayTutorial_K2Node_ComponentBoundEvent_0_OnToggle__DelegateSignature(ToggleValue) end
function UWBP_Settings_Page_Game_C:OnConfirmResetToDefault() end
---@param ToggleValue boolean
function UWBP_Settings_Page_Game_C:BndEvt__WBP_Settings_Page_Game_WBP_Settings_Entry_Choice_Toggle_DisplayAchievementNotifications_K2Node_ComponentBoundEvent_12_OnToggle__DelegateSignature(ToggleValue) end
---@param ToggleValue boolean
function UWBP_Settings_Page_Game_C:BndEvt__WBP_Settings_Page_Game_WBP_Settings_Entry_Choice_Toggle_AutoSkipAlreadySeenEvents_K2Node_ComponentBoundEvent_13_OnToggle__DelegateSignature(ToggleValue) end
---@param InFocusEvent FFocusEvent
function UWBP_Settings_Page_Game_C:OnAddedToFocusPath(InFocusEvent) end
---@param Value double
function UWBP_Settings_Page_Game_C:BndEvt__WBP_Settings_Page_Game_WBP_Settings_Entry_Slider_LowHPFeedbackOpacity_K2Node_ComponentBoundEvent_6_OnSliderValueChanged__DelegateSignature(Value) end
---@param EntryPoint int32
function UWBP_Settings_Page_Game_C:ExecuteUbergraph_WBP_Settings_Page_Game(EntryPoint) end


