---@meta

---@class UWBP_Settings_Page_Video_C : UWBP_Settings_Page_C
---@field UberGraphFrame FPointerToUberGraphFrame
---@field WBP_Button_Generic_Apply UWBP_Button_Generic_C
---@field WBP_Button_Generic_Gamma UWBP_Button_Generic_C
---@field WBP_Button_Generic_RevertToDefault UWBP_Button_Generic_C
---@field WBP_Settings_Entry_Choice_AntiAliasing UWBP_Settings_Entry_Choice_AntiAliasingQuality_C
---@field WBP_Settings_Entry_Choice_AntiAliasingType UWBP_Settings_Entry_Choice_AntiAliasingType_C
---@field WBP_Settings_Entry_Choice_AspectRatio UWBP_Settings_Entry_Choice_AspectRatio_C
---@field WBP_Settings_Entry_Choice_EffectsQuality UWBP_Settings_Entry_Choice_EffectsQuality_C
---@field WBP_Settings_Entry_Choice_PostProcessQuality UWBP_Settings_Entry_Choice_PostProcessQuality_C
---@field WBP_Settings_Entry_Choice_Resolution UWBP_Settings_Entry_Choice_Resolution_C
---@field WBP_Settings_Entry_Choice_ResolutionScale UWBP_Settings_Entry_Choice_ResolutionScale_C
---@field WBP_Settings_Entry_Choice_ScreenMode UWBP_Settings_Entry_Choice_ScreenMode_C
---@field WBP_Settings_Entry_Choice_Toggle_ConstraintHUDAspectRatio UWBP_Settings_Entry_Choice_Toggle_C
---@field WBP_Settings_Entry_Choice_Toggle_VSync UWBP_Settings_Entry_Choice_Toggle_C
---@field WBP_Settings_Entry_FPS UWBP_Settings_Entry_FPS_C
local UWBP_Settings_Page_Video_C = {}

---@param MyGeometry FGeometry
---@param InFocusEvent FFocusEvent
---@return FEventReply
function UWBP_Settings_Page_Video_C:OnFocusReceived(MyGeometry, InFocusEvent) end
function UWBP_Settings_Page_Video_C:RevertGameUserSettingsToDefault() end
function UWBP_Settings_Page_Video_C:SetupValues() end
---@param KeyEvent FKeyEvent
function UWBP_Settings_Page_Video_C:BndEvt__WBP_Settings_Page_Video_WBP_Button_Generic_Apply_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature(KeyEvent) end
function UWBP_Settings_Page_Video_C:BndEvt__WBP_Settings_Page_Video_WBP_Settings_Entry_Choice_ScreenMode_K2Node_ComponentBoundEvent_2_OnChanged__DelegateSignature() end
function UWBP_Settings_Page_Video_C:BndEvt__WBP_Settings_Page_Video_WBP_Settings_Entry_Choice_Resolution_K2Node_ComponentBoundEvent_3_OnChanged__DelegateSignature() end
function UWBP_Settings_Page_Video_C:Construct() end
---@param ToggleValue boolean
function UWBP_Settings_Page_Video_C:BndEvt__WBP_Settings_Page_Video_WBP_Settings_Entry_Choice_Toggle_VSync_K2Node_ComponentBoundEvent_4_OnToggle__DelegateSignature(ToggleValue) end
---@param KeyEvent FKeyEvent
function UWBP_Settings_Page_Video_C:BndEvt__WBP_Settings_Page_Video_WBP_Button_Generic_RevertToDefault_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature(KeyEvent) end
function UWBP_Settings_Page_Video_C:BndEvt__WBP_Settings_Page_Video_WBP_Settings_Entry_Choice_AntiAliasingType_K2Node_ComponentBoundEvent_8_OnAntiAliasingTypeChanged__DelegateSignature() end
---@param KeyEvent FKeyEvent
function UWBP_Settings_Page_Video_C:BndEvt__WBP_Settings_Page_Video_WBP_Button_Generic_Gamma_K2Node_ComponentBoundEvent_5_OnPressed__DelegateSignature(KeyEvent) end
function UWBP_Settings_Page_Video_C:Destruct() end
---@param ToggleValue boolean
function UWBP_Settings_Page_Video_C:BndEvt__WBP_Settings_Page_Video_WBP_Settings_Entry_Choice_Toggle_ConstraintHUDAspectRatio_K2Node_ComponentBoundEvent_6_OnToggle__DelegateSignature(ToggleValue) end
function UWBP_Settings_Page_Video_C:OnResolutionChanged() end
function UWBP_Settings_Page_Video_C:BndEvt__WBP_Settings_Page_Video_WBP_Settings_Entry_Choice_AspectRatio_K2Node_ComponentBoundEvent_7_OnChanged__DelegateSignature() end
function UWBP_Settings_Page_Video_C:OnConfirmResetToDefault() end
---@param EntryPoint int32
function UWBP_Settings_Page_Video_C:ExecuteUbergraph_WBP_Settings_Page_Video(EntryPoint) end


