#pragma once
#include "CoreMinimal.h"
#include "ESpineLocomotionType.generated.h"

UENUM(BlueprintType)
enum class ESpineLocomotionType : uint8 {
    None,
    Idle,
    Walk,
    Run,
    Dash,
    Ride,
    FallingUp,
    FallingNeutral,
    FallingDown,
    DashFallingUp,
    DashFallingNeutral,
    DashFallingDown,
    RideFallingUp,
    RideFallingNeutral,
    RideFallingDown,
    FallingKnockbackUp_Backward,
    FallingKnockbackNeutral_Backward,
    FallingKnockbackDown_Backward,
    FallingKnockbackUp_Forward,
    FallingKnockbackNeutral_Forward,
    FallingKnockbackDown_Forward,
    WallGrab,
    Slide,
    HookAttach,
    SwimIdle,
    SwimMove,
    UnderWaterIdle,
    UnderWaterUp,
    UnderWaterUpLateral,
    UnderWaterDown,
    UnderWaterDownLateral,
    UnderWaterLateral,
    UnderWaterDashUp,
    UnderWaterDashUpLateral,
    UnderWaterDashDown,
    UnderWaterDashDownLateral,
    UnderWaterDashLateral,
    UnderWaterRideUp,
    UnderWaterRideUpLateral,
    UnderWaterRideDown,
    UnderWaterRideDownLateral,
    UnderWaterRideLateral,
    FlyIdle,
    Fly,
    FlyUp,
    FlyDown,
    WallScaling_Idle,
    WallScaling_Forward,
    WallScaling_Backward,
    Stun,
};

